### ISSUE TITLE
get rid of SuPeRfail

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/openmath#1]
The file `tst/test_new` references `SuPeRfail`. It is not clear to me why it does so, nor whether anything uses it. But it would be great if this could be removed.

See also https://github.com/gap-system/gap/issues/560

**Comment by olexandr-konovalov** [comment]
First, observe that it has a _string_ `"SuPeRfail"` there. This particular string appears in `tst/test_new` test file which is autogenerated from `test_new.src` with

```
gap.sh -T -A -b -r < test_new.src
```

and is related to the private content dictionary `cas` which is some pre-2007 code. What I need to do is to switch https://github.com/gap-packages/openmath/blob/master/private/private.g to use READ_COMMAND_REAL and then update the test appropriately.

**Comment by olexandr-konovalov** [comment]
Done in https://github.com/gap-packages/openmath/commit/c5b122b90459e7f0e78317715c1faecddf0f97d5
