### ISSUE TITLE
Rewrite `semigroups` specific code?

### ISSUE THREAD

**Issue by markuspf** [gap-packages/openmath#10]
#9 removes some semigroups specific code that has long been obsolete. It could be rewritten using the `Semigroups` package, if there's a desire for this code.

**Comment by olexandr-konovalov** [comment]
I don't understand why this was reopened while #9 was closed. Will close this after a while unless I will hear anything.

**Comment by fingolfin** [comment]
When PR #9 was merged, this issue was NOT closed.

However, it was closed by accident when https://github.com/gap-packages/openmath/commit/dfdd5d478fa540c1237f0c3f5a82c8ef64de559a was merged. I reopened it then because I did not close it accidentally.

**Comment by olexandr-konovalov** [comment]
Ok, then fine to close it now!
