### ISSUE TITLE
Error in test_new.tst in GAP master branch

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/openmath#26]
As seen in e.g. https://github.com/gap-packages/openmath/runs/5305930402?check_suite_focus=true
```
########> Diff in /home/runner/work/openmath/openmath/gaproot/pkg/openmat\
h/tst/test_new.tst:[92](https://github.com/gap-packages/openmath/runs/5305930402?check_suite_focus=true#step:5:92)
# Input is:
OMGetObject(stream); OM_GAP_OUTPUT_STR; OM_GAP_ERROR_STR; OM_GAP_OUTPUT_STR :=\
 "";; OM_GAP_ERROR_STR := "";;
# Expected output:
true
""
""
# But found:
false
fail
"Unknown Error"
######## 
```

**Comment by fingolfin** [comment]
Tracked down the difference to `OMgapNativeStatementFunc("quit;")` which returned `true` before and now returns `false`... And this in turn boils down to this, which runs in plain GAP without any packages:
```gap
   READ_COMMAND_REAL(InputTextString("quit;"),false);
```
And yes, this code *did* change in the GAP kernel. Indeed, it goes back to [this GAP PR](https://github.com/gap-system/gap/pull/4618), and is explicitly mentioned in [a comment on that PR](https://github.com/gap-system/gap/pull/4618#issuecomment-886565795).

I'll revert this behavior -- while I still think the "new" behavior is "better", the truth is that `READ_COMMAND_REAL` is a horribly hack, and trying to put lipstick on that pig is a pointless, esp. if it breaks existing code. Instead we should add a better API under a new name.

**Comment by fingolfin** [comment]
See https://github.com/gap-system/gap/pull/4847

**Comment by fingolfin** [comment]
Resolved
